spring:
  application:
    name: manga-reader
  # Import .env
  config:
    import: optional:file:.env[.properties]
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
    version: openapi_3_0
